version: '2'


services:
  oracle_reels:
    image: postgres
    container_name: postgresql-bdw
    ports:
      - "15432:5432"
  bdwbackend:
    image: bdw-backend
    container_name: bdwbackend
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - spring.profiles.active=local-docker
    depends_on:
      - postgresql
